# Generated by Django 2.2.6 on 2019-10-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0002_auto_20191031_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tag.Tag')),
            ],
        ),
    ]
